name: "Setup Dependencies"
description: "Setup tools/dependencies"
inputs:
  # Task
  install_task:
    description: "install task if true"
    default: "true"
  task_version:
    description: "version of task to install"
    default: "v3.44.0"

  # Language runtimes / toolchains
  install_go:
    description: "install go if true"
    default: "false"
  install_node:
    description: "install node if true"
    default: "false"
  install_python:
    description: "install python if true"
    default: "false"
  service_path:
    description: "path to service within repo (used to find version file)"
    default: ""

runs:
  using: "composite"
  steps:
    - if: ${{ inputs.install_task == 'true' }}
      uses: supplypike/setup-bin@8e3f88b4f143d9b5c3497f0fc12d45c83c123787
      with:
        uri: "https://github.com/go-task/task/releases/download/${{ inputs.task_version }}/task_linux_amd64.tar.gz"
        name: task
        version: ${{ inputs.task_version }}

    - if: ${{ inputs.install_go == 'true' }}
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version-file: ./${{ inputs.service_path }}/go.mod

    - if: ${{ inputs.install_node == 'true' }}
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version-file: ./${{ inputs.service_path }}/package.json

    - if: ${{ inputs.install_python == 'true' }}
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version-file: ./${{ inputs.service_path }}/pyproject.toml

    - if: ${{ inputs.install_python == 'true' }}
      uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a # v1.4.1


    # TODO: add namespace.sh setup steps
