name: "Setup Dependencies"
description: "Setup tools/dependencies"
inputs:
  # Task
  install_task:
    description: "install task if true"
    default: "true"
  task_version:
    description: "version of task to install"
    default: "v3.44.0"

  # Language runtimes / toolchains
  install_go:
    description: "install go if true"
    default: "false"
  install_node:
    description: "install node if true"
    default: "false"
  install_python:
    description: "install python if true"
    default: "false"
  service_path:
    description: "path to service within repo (used to find version file)"
    default: ""

runs:
  using: "composite"
  steps:
    - if: ${{ inputs.install_task == 'true' }}
      uses: supplypike/setup-bin@1fafb085795af4a3f183502f3a9dffa8f7b83217 # v5.0.0
      with:
        uri: "https://github.com/go-task/task/releases/download/${{ inputs.task_version }}/task_linux_amd64.tar.gz"
        name: task
        version: ${{ inputs.task_version }}

    - if: ${{ inputs.install_go == 'true' }}
      uses: actions/setup-go@1d76b952eb9246b03e20e15a9ef98c6d4af389ef # v5.5.0
      with:
        go-version-file: ./${{ inputs.service_path }}/go.mod
        cache-dependency-path: "./${{ inputs.service_path }}/go.sum"

    - if: ${{ inputs.install_node == 'true' }}
      uses: actions/setup-node@d7a11313b581b306c961b506cfc8971208bb03f6 # v4.4.0
      with:
        node-version-file: ./${{ inputs.service_path }}/package.json
        cache: npm
        cache-dependency-path: ./${{ inputs.service_path }}/package-lock.json

    # Installing poetry before running setup-python to enable using poetry type cache
    - if: ${{ inputs.install_python == 'true' }}
      uses: snok/install-poetry@d526ede1e27960b7b181a5ac53044f552afdaa38 # v1.4.1

    - if: ${{ inputs.install_python == 'true' }}
      uses: actions/setup-python@3d1e2d2ca0a067f27da6fec484fce7f5256def85 # v5.6.0
      with:
        python-version-file: ./${{ inputs.service_path }}/pyproject.toml
        cache: poetry
        cache-dependency-path: ./${{ inputs.service_path }}/poetry.lock

    # TODO: add namespace.sh setup steps
