version: "3"

vars:
  IMAGE_REPO: sidpalas/devops-directive-docker-course-client-react-nginx
  IMAGE_TAG: foobarbaz
  SERVICE_RELEASE_TAG: services/react/client-react

includes:
  utils:
    taskfile: ../../../utils/Taskfile.yaml
    dir: ../../../utils

tasks:
  build-container-image:
    desc: Build container image
    cmds:
      - docker build -t {{.IMAGE_REPO}}:{{.IMAGE_TAG}} .

  build-container-image-multi-arch:
    desc: Build multi-arch container image
    cmds:
      - |
        docker buildx build \
        --platform linux/amd64,linux/arm64 \
        -t {{.IMAGE_REPO}}:{{.IMAGE_TAG}} \
        --push \
        .

  install:
    desc: install dependencies
    cmds:
      - npm install

  install-ci:
    desc: install/download package dependencies
    cmds:
      - npm ci

  run:
    desc: Start react client
    cmds:
      - npm run dev

  test:
    desc: run tests
    cmds:
      - npm run test
