# This is used by the action https://github.com/dorny/paths-filter

# This is effectively serving as a naive target determinator (see: https://blog.swgillespie.me/posts/monorepo-ingredients/)

# ---- services ---------------------------------------------------------------
services/go/api-golang: &api_golang
  - "services/go/api-golang/**"
  - "services/other/api-golang-migrator/**" # db migrations tied to service
  - ".github/actions/setup-dependencies/action.yaml"

services/node/api-node:
  - "services/node/api-node/**"
  - ".github/actions/setup-dependencies/action.yaml"

services/other/api-golang-migrator:
  - *api_golang # db migrations tied to service

services/python/load-generator-python:
  - "services/python/load-generator-python/**"
  - ".github/actions/setup-dependencies/action.yaml"

services/react/client-react:
  - "services/react/client-react/**"
  - ".github/actions/setup-dependencies/action.yaml"
