name: Export GitHub Action Timing Data

on:
  workflow_run:
    workflows:
      - "Build and Push Container Images"
      - "Run Tests"
      - "Release Please"
    types: [completed]

jobs:
  export-otel-trace:
    name: OpenTelemetry Export Trace
    runs-on: ubuntu-24.04
    steps:
      - name: Export Workflow Trace
        uses: corentinmusard/otel-cicd-action@v2.2.4
        with:
          otlpEndpoint: grpc://api.honeycomb.io:443/
          # Formatted as x-honeycomb-team=YOUR_API_KEY
          otlpHeaders: ${{ secrets.HONEYCOMB_OTLP_HEADERS }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          runId: ${{ github.event.workflow_run.id }}
